# Generated by Django 5.2.8 on 2025-11-13 14:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=150, unique=True)),
                ("description", models.TextField(blank=True)),
                ("isListed", models.BooleanField(default=True)),
            ],
            options={"db_table": "category", "ordering": ["name"],},
        ),
        migrations.CreateModel(
            name="Variant",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("variant_type", models.CharField(max_length=150)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("stock", models.PositiveIntegerField(default=0)),
                ("isListed", models.BooleanField(default=True)),
            ],
            options={"db_table": "variant", "ordering": ["variant_type"],},
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("artist_name", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("available_quantity", models.PositiveIntegerField(default=0)),
                ("description", models.TextField(blank=True)),
                ("publishing_date", models.DateField()),
                ("product_imgs", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="Admin.category",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="Admin.variant",
                    ),
                ),
            ],
            options={"db_table": "product", "ordering": ["-created_at"],},
        ),
    ]
