# Generated by Django 5.2.8 on 2025-11-21 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_category_is_deleted_product_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('category_name', models.CharField(max_length=255)),
                ('discount', models.IntegerField()),
                ('is_listed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'offer',
                'ordering': ['-created_at'],
            },
        ),
    ]
