# Generated by Django 5.2.8 on 2025-11-28 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='Admin.product'),
        ),
    ]
