# Generated by Django 5.2.8 on 2026-03-31 05:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_variant_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='is_listed',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='category_name',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='product_name',
        ),
        migrations.AddField(
            model_name='offer',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='offers', to='Admin.category'),
        ),
        migrations.AddField(
            model_name='offer',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='offer',
            name='name',
            field=models.CharField(default='General Offer', max_length=255),
        ),
        migrations.AddField(
            model_name='offer',
            name='offer_type',
            field=models.CharField(choices=[('Percentage', 'Percentage'), ('Flat', 'Flat')], default='Percentage', max_length=20),
        ),
        migrations.AddField(
            model_name='offer',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='offers', to='Admin.product'),
        ),
        migrations.AddField(
            model_name='offer',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='offer',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='offer',
            name='variants',
            field=models.ManyToManyField(blank=True, related_name='offers', to='Admin.variant'),
        ),
    ]
