from .admin_views import *
from .customers_views import *
from .category_views import *
from .product_views import *
from .offers_views import *
from .orders_views import *
from .wallet_views import *
from .dashboard_views import *
from .sales_report_views import *
