# Generated by Django 5.2.8 on 2025-11-11 15:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customuser",
            name="pro_image",
            field=models.ImageField(
                blank=True, max_length=255, null=True, upload_to="profile_images/"
            ),
        ),
    ]
