# Generated by Django 5.2.8 on 2025-11-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0002_customuser_created_at_customuser_pro_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="mobile",
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
