# Generated by Django 5.2.8 on 2026-01-07 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Admin", "0004_variant_product"),
        ("User", "0004_cart_cartitems"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitems",
            name="varient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Admin.variant",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cartitems", unique_together={("cart", "product", "varient")},
        ),
        migrations.AlterModelTable(name="cartitems", table="cart_items",),
    ]
