# Generated by Django 5.2.8 on 2026-01-12 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0007_address_order_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="return_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Confirmed", "Confirmed"),
                    ("Shipped", "Shipped"),
                    ("Delivered", "Delivered"),
                    ("Cancelled", "Cancelled"),
                    ("Returned", "Returned"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
