# Generated by Django 5.2.8 on 2026-03-27 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0010_wallet_wallettransaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Confirmed", "Confirmed"),
                    ("Shipped", "Shipped"),
                    ("Delivered", "Delivered"),
                    ("Cancel Requested", "Cancel Requested"),
                    ("Cancelled", "Cancelled"),
                    ("Return Requested", "Return Requested"),
                    ("Returned", "Returned"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Confirmed", "Confirmed"),
                    ("Shipped", "Shipped"),
                    ("Delivered", "Delivered"),
                    ("Cancel Requested", "Cancel Requested"),
                    ("Cancelled", "Cancelled"),
                    ("Return Requested", "Return Requested"),
                    ("Returned", "Returned"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
