# Generated by Django 5.2.8 on 2026-03-31 05:04
# Modified: backfill referral codes for existing users before adding unique constraint

import secrets
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_referral_codes(apps, schema_editor):
    """Assign unique referral codes to existing users who don't have one."""
    CustomUser = apps.get_model('User', 'CustomUser')
    for user in CustomUser.objects.filter(referral_code__isnull=True):
        while True:
            code = secrets.token_urlsafe(6).upper()[:8]
            if not CustomUser.objects.filter(referral_code=code).exists():
                user.referral_code = code
                user.save(update_fields=['referral_code'])
                break

    # Also fix empty string codes (if any)
    for user in CustomUser.objects.filter(referral_code=''):
        while True:
            code = secrets.token_urlsafe(6).upper()[:8]
            if not CustomUser.objects.filter(referral_code=code).exists():
                user.referral_code = code
                user.save(update_fields=['referral_code'])
                break


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0012_order_discount_amount_coupon_order_coupon_and_more'),
    ]

    operations = [
        # Step 1: Add new fields (without unique constraint yet on referral_code)
        migrations.AddField(
            model_name='coupon',
            name='created_for_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_coupons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coupon',
            name='is_referral_coupon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals_made', to=settings.AUTH_USER_MODEL),
        ),

        # Step 2: Backfill referral codes for existing users
        migrations.RunPython(backfill_referral_codes, migrations.RunPython.noop),

        # Step 3: Now apply unique constraint (all rows have a unique code)
        migrations.AlterField(
            model_name='customuser',
            name='referral_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),

        # Step 4: Create the Referral tracking model
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_event', to='User.coupon')),
                ('referred_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_record', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
